Simulation = "CollectiveKeyGeneration"
BF = 2
Rounds = 1
Suite = "Ed25519"

# SingleHost = True

# here you can have for different depth to test.
# keep in mind that if the number of nodes will be Sum(BF^i) i [0,Depth]
Hosts, Servers
3,3


