Simulation = "CollectivePublicKeySwitching"
Servers = 5
BF = 2
Rounds = 1
Suite = "Ed25519"
# SingleHost = True

# number nodes = Sum(BF^i) i [0,Depth]
Hosts, Servers, ParamsIdx, SwitchDegree
3,3,0,1
3,3,1,1
3,3,2,1
3,3,3,1
8,8,0,1
8,8,1,1
8,8,2,1
8,8,3,1
16,16,0,1
16,16,1,1
16,16,2,1
16,16,3,1


